#:schema node_modules/wrangler/config-schema.json

compatibility_flags = ["nodejs_compat"]

name = "awwbot"
main = "./src/server.ts"
compatibility_date = "2024-06-05"


# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
